Refactor bus mapping by moving eth and evm types outside
appliedzkp/zkevm-circuits pull request #290
Opened 2022-01-19 03:41 UTC by scroll-dev

Step-1 of PR https://github.com/scroll-tech/zkevm-circuits/pull/70

Related discussion in issue https://github.com/appliedzkp/zkevm-circuits/issues/272

### Summary

1. Move `eth_types.rs` of bus-mapping to `lib.rs` of  new sub-crate eth-types.
2. Move all files of `evm` of bus-mapping to `evm_types` of eth-types except `opcodes`.
3. Update code and test of bus-mapping and zkevm-circuits.

2022-01-19 16:13 UTC, ed255 requested changes
Thanks for the contribution!  Overall looks really good.  Please take a look at my comments, they are small details.

2022-01-19 16:15 UTC, ed255 commented
Also it seems that there are conflicts with main (probably from a recently merged PR) that you'll need to address.

2022-01-19 21:49 UTC, CPerezz commented on eth-types/Cargo.toml
> +authors = ["CPerezz <c.perezbaro@gmail.com>"]
Of course! I suggested that a long time ago!!!!

2022-01-19 21:49 UTC, CPerezz commented on eth-types/src/evm_types.rs
> +pub struct RWCounter(pub usize);
I do completely agree!

2022-01-19 21:54 UTC, CPerezz reviewed
LGTM modulo @ed255 's comments

2022-01-20 07:57 UTC, silathdiir commented on eth-types/src/error.rs
>  use std::error::Error as StdError;
I will try to fix it in another PR. Thanks.

2022-01-20 10:07 UTC, ed255 commented on eth-types/src/error.rs
>  use std::error::Error as StdError;
Opened an issue for that https://github.com/appliedzkp/zkevm-circuits/issues/294

2022-01-21 00:22 UTC, silathdiir commented
Hi @ed255 and @CPerezz , it seems that the CI is broken on `main` branch. Could you help on that if you have time? Thanks.

2022-01-21 03:22 UTC, HAOYUatHZ commented
> Hi @ed255 and @CPerezz , it seems that the CI is broken on `main` branch. Could you help on that when you have time? Thanks.

@silathdiir wait for https://github.com/appliedzkp/zkevm-circuits/pull/296 being merged then it should work

2022-01-21 03:23 UTC, HAOYUatHZ commented
Or you could cherry-pick https://github.com/appliedzkp/zkevm-circuits/pull/296 for now

2022-01-21 09:41 UTC, CPerezz approved these changes
LGTM

2022-01-21 10:58 UTC, ed255 approved these changes
LGTM!

2022-01-21 11:00 UTC, merged